version: 2
jobs:
  build:
    working_directory: /usr/src/app
    environment:
      OPENCOLLECTIVE_FORCE: "true"
    docker:
      - image: banian/node
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: npm-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev npm i

      # Keep cache
      - save_cache:
          key: npm-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      # Build
      - run:
          name: Build
          command: yarn build

      # Test
      - run:
          name: Tests
          command: yarn test

      # Coverage
      - run:
          name: Coverage
          command: yarn coverage
